import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'
import StoreInitializer from '@/store/StoreInitializer'
import { useAuth } from '@/hooks/useAuth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const { fetchUser } = useAuth()

    const user = await fetchUser()

    return (
        <html lang="en">
            <body
                className={cn(
                    inter.className,
                    'bg-white text-base font-normal text-black antialiased',
                )}
            >
                <StoreInitializer auth={user} />
                <main>{children}</main>
                <Toaster />
            </body>
        </html>
    )
}
